### ISSUE TITLE
Инструкция по установке

### ISSUE THREAD

**Issue by Oloshka** [Bashka/vim_git#2]
Интересный плагин, но не мешало бы добавить инструкцию по установке.

**Comment by Bashka** [comment]
Плагин устанавливается по аналогии с любым другим в Vim, но имеет зависимость в виде [vim_lib](http://vimawesome.com/plugin/vim-lib).

**К примеру с помощью Vundle его можно установить так**
В .vimrc записываем:
Plugin 'bashka/vim_lib'
Plugin 'bashka/vim_git'

Затем выполняем:
:source %
:PluginInstall

**Comment by Oloshka** [comment]
Зависимость от vim_lib была неочевидным местом.
Вместе с плагином поставляется какой-нибудь файл дефолтного биндинга клавиш?

**Comment by Bashka** [comment]
Нет, весь биндинг выполняется самим пользователем. Плагин только реализует пункты в меню.

Лично я пользуюсь таким биндингом:
'status':      'gs
'log':         'gl
'branchList':  'gb
'tagList':     'gt
'addCurrent':  'ga
'addAll':      'gA
'commit':      'gc
'commitAll':   'gC
'pushCurrent': 'go
'pullCurrent': 'gi
'remoteList':  'gr

**Comment by Oloshka** [comment]
Ок
